version: '3.9'
services:

  clematis-poc-pomodoro:
    container_name: clematis-poc-pomodoro
    image: clematis.poc.pomodoro:latest
    ports:
      - "18084:3000"
    volumes:
      - ./nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - clematis
    restart: unless-stopped

networks:
  clematis:
    driver: bridge
