version: '3.9'
services:
  clematis-poc-pomodoro:
    container_name: clematis-poc-pomodoro
    image: clematis.poc.pomodoro:latest
    ports:
      - '18084:3000'
    volumes:
      - ssl_certs:/opt/software/certs:ro
    networks:
      - clematis
    restart: unless-stopped

volumes:
  ssl_certs:
    name: jenkins_ssl_certs
    external: true

networks:
  clematis:
    driver: bridge
